### PR TITLE
Improvements on Get single article routes

### PR DESCRIPTION
**Pull request by agusbusta**
# Update GET /article/{article_id} endpoint response format

## Description
Updated the GET /article/{article_id} endpoint to match the response format of the GET /articles endpoint, ensuring consistency across the API.

## Changes Made
- Added category and bot information to the response
- Included new fields: category_name, category_icon, bot_icon, and type
- Standardized response format between valid and unwanted articles
- Added proper handling for null values in unwanted articles
- Improved query efficiency by using joins and specific field selection

## Response Format
The endpoint now returns the following fields:
- id: Article ID
- title: Article title
- content: Article content
- image: Article image URL
- url: Article URL
- date: Article date
- bot_id: Bot identifier
- bot_icon: Bot icon URL
- created_at: Creation timestamp
- updated_at: Last update timestamp
- top_story: Boolean flag for top stories
- category_name: Article category name
- category_icon: Category icon URL
- type: Article type ('valid' or 'bin')

### CODE REVIEW

**Comment by agusbusta** [comment]
# Consolidate and Enhance Articles API Endpoint

## Description
I have consolidated multiple article endpoints into a single, more powerful `/articles` endpoint. This update improves code maintainability and provides enhanced filtering capabilities.

## Key Changes
- Merged `/articles/all` and `/articles` into a single `/articles` endpoint
- Added new filtering capabilities:
  - Filter by bot name (case insensitive)
  - Filter by category name
  - Filter by top stories
  - Toggle inclusion of valid/invalid articles
- Enhanced response format to include:
  - Bot information (icon)
  - Category details (name, icon)
  - Top story flag
- Improved query efficiency with proper database joins
- Removed deprecated endpoints

## Query Parameters
- `page`: Page number (default: 1)
- `per_page`: Items per page (default: 10)
- `search`: Search in title/content
- `bot`: Filter by bot name
- `category`: Filter by category name
- `top_stories`: Show only top stories
- `bin`: Include unwanted articles
- `valid_articles`: Include valid articles

## Testing
- Tested pagination
- Verified all filter combinations
- Confirmed response format consistency
- Validated error handling

**Comment by daviddflix** [comment]
**Suggested Improvements & Recommendations:**

I just tested the `/articles` endpoint and noticed an issue with the `category_id` attribute. Here’s what I found and what I suggest:

1. **Category Attribute Issue**:  
   I see that the endpoint is throwing an error: `"Internal server error: type object 'Article' has no attribute 'category_id'."` This suggests that `category_id` or a related category field is missing from the `Article` model or not properly referenced. Before sending the fix, I recommend reviewing the `Article` model and the query logic to ensure that the `category_id` (or the appropriate category field) is properly defined, mapped, and joined.

Reference:
image


2. **Verify Using Swagger and Postman**:  
   I also noticed that the update might not have been thoroughly tested using Swagger’s UI-based testing tool. I recommend that you not only test using Postman but also perform a thorough check using Swagger’s documentation UI. This will help you confirm that all pagination, filtering, and category-based queries work as expected and match the documented behavior.

3. **Endpoint Removal**:  
   While cleaning up deprecated endpoints, I noticed that `/article` should also be removed as it’s now redundant. Additionally, make sure that `DELETE /article` is not removed since it’s still required. Double-check which endpoints must remain and which should be removed to maintain the intended functionality I needed.

4. **Consistent Response Format**:  
   I recommend ensuring that the `/analyses` endpoint **matches** the response object format of the `/article/{article_id}` endpoint for consistency across the API.

**Comment by agusbusta** [comment]
@daviddflix Changes are ready!

**Comment by daviddflix** [comment]
**Suggested Improvements & Recommendations:**

I just tested the `/articles` endpoint and noticed a few issues and opportunities for improvement:

1. **Category Attribute Issue**:  
   I see that the `/articles` endpoint is throwing an error: `"Internal server error: type object 'Article' has no attribute 'category_id'."` This indicates that `category_id` or the related category field isn’t properly defined in the `Article` model or the join/query. Before sending the fix, I recommend reviewing your models and queries to ensure that the `category_id` (or an equivalent field) is properly defined and referenced.

Evidence:
image


2. **Testing Using Swagger and Postman**:  
   I noticed that the updates might not have been fully verified with the Swagger UI. I recommend testing the `/articles` endpoint not just with Postman, but also through Swagger’s documentation UI. This step will help confirm that all the filters (pagination, search, bot, category, top_stories, bin, valid_articles) and the response structure work as expected.

3. **Endpoint Cleanup**:  
   While removing deprecated endpoints, it appears that `/article` should also be removed. However, be careful to keep the `DELETE /article` endpoint intact since that one still needs to remain. Please verify that only the intended deprecated endpoints are removed.

4. **Consistent Response Format**:  
   I suggest ensuring that the `/articles` endpoint returns a response format identical to the `/article/<int:article_id>` endpoint. Since `/articles` represents a collection of articles, each article object in the returned list should have the exact same fields and structure as the single article object returned by `/article/<int:article_id>`. This consistency helps maintain predictable responses and eases integration for clients.

**Comment by agusbusta** [comment]
hey @daviddflix, its ready now!  Im testing using UI also 
Screenshot 2024-12-20 at 3 06 13 PM

**Comment by agusbusta** [comment]
Category Attribute Issue, .join bug fixed and testing using UI and ThunderClient: 
Screenshot 2024-12-20 at 4 30 41 PM

Screenshot 2024-12-20 at 4 30 49 PM

Swagger and Articles.py Deprecated or unused Routes erased:
Screenshot 2024-12-20 at 4 40 46 PM

**Comment by daviddflix** [comment]
Hey @agusbusta,

Great job on addressing the previous issues! Everything is looking much better now. However, after testing the `/articles` endpoint, I noticed that when I try to retrieve only top stories, it doesn’t behave as expected.

**Current Behavior:**
If I request just top stories (without specifying `bin` or `valid_articles`), I receive the following error:
`{ "data": null, "error": "At least one article type (bin or valid_articles) must be selected", "success": false }`


**Intended Behavior:**
If a user only wants top stories, they should be able to request them without needing to specify `bin` or `valid_articles`. In other words, `top_stories=true` should return just the top stories, regardless of whether `bin` or `valid_articles` are provided.

**Suggested Improvement:**
Please adjust the logic so that if `top_stories` is requested alone, the endpoint returns only top stories without requiring any additional parameters.

Thanks again for your hard work and for making these improvements!

**Comment by agusbusta** [comment]
hey @daviddflix changes are ready!

**Pull request closed without merging**
