### PR TITLE
Test/new scrapper flow

### PR DESCRIPTION
**Pull request by agusbusta**
RSS Feed Scraping Enhancements
Overview
This pull request introduces significant improvements to our news scraping functionality, focusing on efficient RSS feed processing and better handling of article metadata.
Key Changes

WebScraper Class Modification

Enhanced the scrape_rss method to efficiently parse RSS feeds using feedparser.
Improved logging and error handling in the RSS scraping process.

fetch_urls Function Refactoring

Adapted fetch_urls to utilize the improved scrape_rss method of WebScraper.
Modified the return structure to include both article titles and URLs.

fetch_news_links Function Update

Updated to work with the new data structure returned by fetch_urls.
Improved handling of article titles and URLs throughout the processing pipeline.

Error Handling and Logging

Enhanced error reporting and logging across all modified components.
Improved visibility into the scraping process, including RSS feed parsing details.

Performance Optimization

Streamlined the RSS feed processing, potentially improving scraping speed and efficiency.

### CODE REVIEW

**Comment by daviddflix** [comment]
# Webscraper Framework Improvements

Thank you for your work on the news bot framework. To improve the organization and readability of the code, please consider the following suggestions:

## Folder Structure

Create a `webscraper` folder with the following structure:
webscraper/
├── init.py
├── webscraper.py
├── filters.py
├── analyzer.py
├── image_generator.py



## File Contents and Responsibilities

### 1. `__init__.py`

Create this file to make the folder a Python package. Include the main class that will be used as an entry point:

```python
from .webscraper import WebScraper

class NewsScraper:
    def __init__(self, url, category_id, bot_id):
        self.url = url
        self.category_id = category_id
        self.bot_id = bot_id
        self.scraper = WebScraper(url)
        # Initialize other components

    def run(self):
        # Implement the main workflow here
        pass
```

### 2. `webscraper.py`
This file should contain the WebScraper class responsible for fetching news from Google News

### 3. `filters.py`
Implement all filter functions in this file

```python
def datetime_checker(date):
    # Implement datetime checking logic
    pass

def url_checker(url, db_connection):
    # Check if URL has been analyzed before
    pass

def content_filter(content, blacklist, keywords):
    # Implement content filtering logic
    pass
```

### 3. `analyzer.py`
Create this file for content analysis functionality - perplexity analysis

```python
def analyze_content(content):
    # Implement content analysis using Perplexity
    pass
```

### 3. `image_generator.py`
Add this file for image generation

```python
def generate_image(analysis):
    # Implement image generation based on analysis
    pass
```

**Review by daviddflix — CHANGES_REQUESTED** [review]
## Pull Request Review Feedback

There News Bot Scrapper is well organized, nice job! 

Please address these details.

__init__.py:
- Please check the indentation of the send_NEWS_message_to_slack_channel in the run method; the indentation could lead to an error.

- Run method: this method is not validating the datetime, although this is done automatically by Google, we should also check it, please ensure to use the filter function datetime_checker

### Datetime filter to implement (Dummy code)

```python
def datetime_checker(date_string: str) -> bool:
    """
    Check if the given date string is valid and recent.

    Args:
        date_string (str): The date string to check.

    Returns:
        bool: True if the date is valid and within the last 24 hours, False otherwise.
    """
    date_formats = [
        "%Y-%m-%d",
        "%d-%m-%Y",
        "%Y/%m/%d",
        "%d/%m/%Y",
        "%B %d, %Y",
        "%d %B %Y",
        "%Y-%m-%dT%H:%M:%S",
        "%Y-%m-%d %H:%M:%S",
    ]

    for date_format in date_formats:
        try:
            parsed_date = datetime.strptime(date_string, date_format)
            current_date = datetime.now()
            date_difference = current_date - parsed_date

            # Check if the date is within the last 24 hours
            if date_difference.total_seconds() <= 24 * 60 * 60 and date_difference.total_seconds() >= 0:
                return True
            else:
                return False
        except ValueError:
            continue

    # If no valid date format is found
    return False
```

## Note: 
self.scraper.scrape_rss() returns the date, which can be used to validate the incoming articles

- After some manual tests, this error comes when trying to send the new articles to Slack: 

```terminal
---Slack API Error Details---: {'ok': False, 'error': 'invalid_blocks', 'errors': ['downloading image failed [json-pointer:/blocks/1/image_url]'], 'response_metadata': {'messages': ['[ERROR] downloading image failed [json-pointer:/blocks/1/image_url]']}}
{'ok': False, 'error': 'invalid_blocks', 'errors': ['downloading image failed [json-pointer:/blocks/1/image_url]'], 'response_metadata': {'messages': ['[ERROR] downloading image failed [json-pointer:/blocks/1/image_url]']}}
{'date': 'Mon, 07 Oct 2024 19:48:28 GMT', 'server': 'Apache', 'vary': 'Accept-Encoding', 'x-slack-req-id': 'a5777c90ca98bc665af52decc494b727', 'x-content-type-options': 'nosniff', 'x-xss-protection': '0', 'pragma': 'no-cache', 'cache-control': 'private, no-cache, no-store, must-revalidate', 'expires': 'Sat, 26 Jul 1997 05:00:00 GMT', 'content-type': 'application/json; charset=utf-8', 'x-accepted-oauth-scopes': 'chat:write', 'x-oauth-scopes': 'incoming-webhook,app_mentions:read,channels:history,channels:read,chat:write,chat:write.customize,commands,files:read,groups:history,im:history,mpim:history,im:write', 'access-control-expose-headers': 'x-slack-req-id, retry-after', 'access-control-allow-headers': 'slack-route, x-slack-version-ts, x-b3-traceid, x-b3-spanid, x-b3-parentspanid, x-b3-sampled, x-b3-flags', 'strict-transport-security': 'max-age=31536000; includeSubDomains; preload', 'referrer-policy': 'no-referrer', 'x-slack-unique-id': 'ZwQ7Cb-rJSEK5PM4EJu5hQAAEAA', 'x-slack-backend': 'r', 'access-control-allow-origin': '*', 'content-length': '221', 'via': '1.1 slack-prod.tinyspeck.com, envoy-www-iad-bnfklrik, envoy-edge-iad-ghtmdody', 'x-envoy-attempt-count': '1', 'x-envoy-upstream-service-time': '3203', 'x-backend': 'main_normal main_canary_with_overflow main_control_with_overflow', 'x-server': 'slack-www-hhvm-main-iad-amur', 'x-slack-shared-secret-outcome': 'no-match', 'x-edge-backend': 'envoy-www', 'x-slack-edge-shared-secret-outcome': 'no-match', 'connection': 'close'}       
[INFO] Analyzing URL: https://news.google.com/rss/articles/CBMihwFBVV95cUxNR0RjeFB4Rkk4RnVSOEpmMjlab3psXzVLYXZDSUpzdHlsRTdaeWFud0YxVUl1YzJBeDkwb04waWJlX05CX21CZVNFdmRQRWdLeHR2Q2d6UmtCN25nODFVR3FvOWRlMUtaTll2WUZ0NlRGUmNVVXgwc3RBbnBBSU85NEVXY3JIYlnSAYwBQVVfeXFMTU5NLTVtODVrMnJaejhYa1hDZERDSjY0R0tnQ21lR3ZEZjNxSTdJazNVZzBaemplRWpNc0pFczZ6czBHMFZTZlVraGNoUk1Fa2hncU9ZYVFORUZWRi14ZlVNUkRCNWhKT3g1RmduWnVUbzlOUXRuTVVLY19iQThKazA1eFZqMnItSlRjalk?oc=5
```


## Important: The activation and deactivation of a bot, category and global activation should always follow this flow:

- Take parameter.
- Validate its fields
- Schedule
- Set to true the is_active field

### Please ensure this process is being followed in the activation endpoints.

# Endpoints Review

## Categories
- toggle_category_coins: this endpoint is not validating properly the fields before activating the bots
- toggle_all_coins: this endpoint is validating the fields but not all of the required one.

## Suggestion: you can reuse the utility functions you just defined in bots.py which are:

- validate_bot_for_activation
- schedule_bot
- deactivate_bot

**Comment by agusbusta** [comment]
Screenshot 2024-10-08 at 3 07 32 PM

Slack fixed! and all solved.

**Comment by agusbusta** [comment]
@daviddflix ready to review

**Pull request merged**
